# When this file is being evaluated, the following variables will be evaluated:
# - $D: $DOT
# - $E: /etc
# - $H: $HOME
# - $O: /opt
# - $R: /root
# - $S: /run/secrets
# - $V: /mnt/volume
engine-rooms:
  dbmac:
    user: nörd
    symlinks:
      $D/rclone: $H/.config/rclone
  capella-7.0.0:
    user: techuser
    original-entrypoint:
      - /bin/su
      - techuser
      - -c
      - /bin/bash /home/techuser/.startup.sh
    symlinks:
      $D/zsh/env/ALL_HOSTS.zsh: $E/zsh/zshenv
      $D/zsh/profile/ALL_HOSTS.zsh: $E/zsh/zprofile
  ja:
    user: nörd
  raspi5:
    user: nörd

symlinks:
  $D/gdbextension.py: $H/.gdbextension.py
  $D/gdbinit: $H/.gdbinit
  $D/git_askpass.py: $E/git_askpass.py
  $D/gitconfig: $H/.gitconfig
  $D/gitconfig_dbgitlab: $V/dev/dbgitlab/.gitconfig
  $D/gitconfig_github: $V/dev/github/.gitconfig
  $D/gitconfig_gitlab: $V/dev/gitlab/.gitconfig
  $D/github-copilot: $H/.config/github-copilot
  $D/gitignore: $H/.gitignore
  $D/gitmessage: $H/.gitmessage
  $D/gnupg: $H/.gnupg
  $D/ipython: $H/.ipython
  $D/jupyter: $H/.jupyter
  $D/kitty-config: $H/.config/kitty
  $D/nvim-config: $H/.config/nvim
  $D/pdbrc.py: $H/.pdbrc.py
  $D/pdbrc: $H/.pdbrc
  $D/pygmentsstyles.py: $H/pygmentsstyles.py
  $D/vimrc: $H/.vimrc
  $D/zsh/env/ALL_HOSTS.zsh: $E/zshenv
  $D/zsh/p10k.zsh: $H/.p10k.zsh
  $D/zsh/profile/ALL_HOSTS.zsh: $E/zprofile
  $D/zsh/zshrc: $H/.zshrc
  $S/keepass_db: $H/keepass.kdbx
  $V/cache: $H/.cache
  $V/cargo: $H/.cargo
  $V/dev: $H/dev
  $V/m2: $H/.m2  # Maven cache
  $V/npm: $H/.local/share/npm
  $V/nvim/share: $H/.local/share/nvim
  $V/nvim/state: $H/.local/state/nvim
  $V/nvm: $H/.nvm  # Node Version Manager
  $V/pyenv: $H/.pyenv
  $V/rustup: $H/.rustup
  $V/zsh_history: $H/.zsh_history
